# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

# every 3rd number in the sequence is even. this makes computation simpler.

def fib(n):
    sum_even = 0
    a, b = 1, 2
    while b <= n:
        sum_even += b
        a, b = a + 2*b, 2*a + 3*b
    return sum_even

print(fib(4000000))


